# This params.yaml overrides the theme's default params.yaml.
# A full list of available params with their default values can be found in the theme's config/_default/params.yaml file.
favicon: img/favicon.png

footer:
  since: 2023

sidebar:
  # emoji: 🍥
  subtitle: 日拱一卒，终成大师
  avatar: img/wujin-master.jpg

comments:
  enabled: true
  provider: giscus

  giscus:
    repo: "un-spoken/un-spoken.github.io"
    repoId: "R_kgDOKvGc7Q"
    category: "General"
    categoryId: "DIC_kwDOKvGc7c4DAq0I"
    mapping: "pathname"
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: "top"
    lightTheme: "light"
    darkTheme: "dark_dimmed"
    lang: "zh-CN"

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: taxonomy
      params:
        limit: 10
        taxonomy: tags
        icon: tag
    - type: taxonomy
      params:
        limit: 10
        taxonomy: categories
        icon: categories
  page:
    - type: toc
